//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSDMMusicdotNet.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[free]\r\n购买原地址 Original Site：[packagelink/]\r\n封面 Cover：\r\n[cover/]\r\n[hr]\r\n[spoiler=专" +
            "辑信息 Album Infomaton]\r\n标题 Title：[albumtitle/]\r\n艺术家 Artist：[artistname/]\r\n发售日 Rele" +
            "ased Date：[releasedate/]\r\n解析度 Resolution：[resolution/]\r\n曲目数 Track Number：[trackn" +
            "umber/]\r\n[/spoiler]\r\n[spoiler=介绍原文 Introduction (Japanese)]\r\n[introduction/]\r\n[/" +
            "spoiler]\r\n[hr]\r\n[spoiler=介绍摘要译文 Translated Introduction Summary]\r\n中文：\r\n\r\nEnglish" +
            "：\r\n\r\n[/spoiler]\r\n[hr]\r\n[spoiler=曲目表 Track List]\r\n[tracklist/]\r\n[/spoiler]\r\n[hr]\r" +
            "\n自购证明 Certification：\r\n[hide=999999][certification/][/hide] \r\n[hr]\r\n[spoiler=听前提示" +
            " Tips before you listen to music]\r\n推荐的享受高解析度资源的方式Recommend ways to open HI-RES m" +
            "usic files：\r\n计算机 Computer：Groove Music for Windows 10，Windows Media Player，fooba" +
            "r2000 ……\r\n手机 Smartphone：海贝音乐 Hiby Music，NePlayer，Android System Music，foobar2000" +
            " ……\r\n[/spoiler]\r\n[hr]\r\n注意！当您购买下本帖时，就默认视为同意以下最终用户协议。\r\nPay attention please, if yo" +
            "u buy this album from here, you will be regard as that you have agreed the EULA " +
            "which shows below.\r\n1.禁止非授权转载，禁止所有形式的对本帖中的付费文件进行直接非授权转载（包括网易云音乐、电台等），但允许转载本帖链接\r\n" +
            "1.You cannot share the files secondly without sharer\'s permission. But it is per" +
            "missed that you can share the link of this page\r\n2.禁止转码，即禁止翻录或转换为MP3或使文件MD5改变等的行" +
            "为 \r\n2.You cannot transcode FLAC to MP3 or any other things to change MD5 of file" +
            "s.\r\n3.二次分享时需使用本帖链接，而非本帖的百度云链接或二次分享的百度云链接或其他任何形式直接分享文件或文件夹链接\r\n3.It is important t" +
            "hat you cannot share links of files below directly but you can share link of thi" +
            "s page. \r\n4.一切以中文版最终用户协议为准\r\n4.The English version is based on the Chinese versio" +
            "n. So if you have any question of the English version, please use the Chinese ve" +
            "rsion. \r\n[/free] \r\n下载前务必阅读最终用户协议\r\nPlease read EULA before downloading forcely\r\n度" +
            "盘 Baidu Cloud Drive：\r\n[bd1/]\r\n带恢复压缩包度盘 Baidu Cloud Drive (rar5 5%) :\r\n[bd2/]\r\n无法" +
            "连接到百度云或对百度云限速反感的 for User who cannot connect to Baidu Cloud Drive： \r\nMEGA:[mega1" +
            "/]")]
        public string BodyTemplate {
            get {
                return ((string)(this["BodyTemplate"]));
            }
        }
    }
}
